---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: |
  https://producerplayer.services.pbskids.org/show-list/?available=public&shows={{ pbs_kids_show_id }}&sort=-encored_on&type=full_length&page=1
  https://producerplayer.services.pbskids.org/show-tracking
polling_headers: content-type=application/json
polling_body:
id: 110655
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Show the latest videos available on the PBS Kids app and website.
  github_url: https://github.com/stephenyeargin/trmnl-pbs-kids
  learn_more_url: https://pbskids.org/
  email_address: stephen@yearg.in
- keyname: pbs_kids_show_id
  name: Show
  description: Select a show to see the latest available videos, e.g. Sesame Street
  field_type: select
  options:
  - Acoustic Rooster: acoustic-rooster
  - Alma's Way: almas-way
  - Arthur: arthur
  - Brambletown: brambletown
  - 'CET Parents ': cet-parents
  - CET/ThinkTV Education: cetthinktv-education
  - Carl the Collector: carl-the-collector
  - City Island: city-island
  - Clifford the Big Red Dog: clifford-big-red-dog
  - Clifford's Puppy Days: cliffords-puppy-days
  - Crafts for Kids: crafts-kids
  - Curious George: curious-george
  - Cyberchase: cyberchase
  - Daniel Tiger's Neighborhood: daniel-tigers-neighborhood
  - Design Squad: design-squad-nation
  - Dinosaur Train: dinosaur-train
  - Donkey Hodie: donkey-hodie
  - Dot's Spot: dots-spot
  - Elinor Wonders Why: elinor-wonders-why
  - FETCH! with Ruff Ruffman: fetch-with-ruff-ruffman
  - Family Math: family-math
  - Family Math en Español: family-math-en-espanol
  - Fizzy's Lunch Lab: fizzys-lunch-lab
  - Hero Elementary: hero-elementary
  - Jamming On the Job: jamming-on-the-job
  - Jelly, Ben & Pogo: jelly-ben-pogo
  - Keyshawn Solves It: keyshawn-solves-it
  - Let's Go Luna!: lets-go-luna
  - Let's Talk: lets-talk
  - Literacy Tips For All Ages: literacy-tips-all-ages
  - Lyla in the Loop: lyla-loop
  - Martha Speaks: martha-speaks
  - Maya & Miguel: maya-miguel
  - Mecha Builders: mecha-builders
  - Meet the Helpers: meet-helpers
  - Mega Wow: mega-wow
  - Milo: milo
  - Mister Rogers' Neighborhood: mister-rogers
  - Molly of Denali: molly-of-denali
  - Mystery League: mystery-league-pbs-kids
  - Nature Cat: nature-cat
  - Odd Squad: odd-squad
  - OddTube: odd-tube
  - Oh Noah!: oh-noah
  - PBS KIDS: pbs-kids
  - PBS KIDS Rocks!: pbs-kids-rocks
  - PBS KIDS Talk About: pbs-kids-talk-about
  - 'PBS KIDS: Activity Challenge': pbs-kids-activity-challenge
  - 'PBS KIDS: Get Moving': pbs-kids-get-moving
  - PBS Western Reserve Educational Productions: western-reserve-public-media-educational-productions
  - Parent Hacks: parent-hacks
  - Parentalogic: parentalogic
  - Parenting Minutes: parenting-minutes
  - Peg + Cat: peg
  - Phoebe & Jay: phoebe-jay
  - Pinkalicious & Peterrific: pinkalicious-and-peterrific
  - Plum Landing: plum-landing
  - Ready Jet Go: ready-jet-go
  - Rocket Saves the Day: rocket-saves-the-day
  - Rosie's Rules: rosies-rules
  - SUPER WHY!: super-why
  - SciGirls: scigirls
  - Scribbles and Ink: scribbles-and-ink
  - Search It Up!: search-it-up
  - Sesame Street: sesame-street
  - Sid the Science Kid: sid-science-kid
  - Skillsville: skillsville
  - Splash and Bubbles: splash-and-bubbles
  - Super Why's Comic Book Adventures: super-whys-comic-book-adventures
  - The Cat in the Hat: cat-in-the-hat
  - The Not-Too-Late Show with Elmo: not-too-late-show-elmo
  - The Ruff Ruffman Show: ruff-ruffman-show
  - Through the Woods: through-woods
  - Tiny Time Travel: tiny-time-travel
  - Together We Can: together-we-can
  - WOSU Specials: wosu-specials
  - Weather Hunters: weather-hunters
  - What Can You Become?: what-can-you-become
  - What's Good?: whats-good
  - Wild Kratts: wild-kratts
  - Word World: word-world
  - Word of the Week: word-of-the-week
  - WordGirl: wordgirl
  - Work It Out Wombats!: work-it-out-wombats
  - Xavier Riddle and the Secret Museum: xavier-riddle-and-secret-museum
  - You, Me, Community: you-me-community
  - 'iQ: smartparent': iq-smartparent
name: PBS Kids
refresh_interval: 1440
